version: '3.8'

services:
  postgres_db:
    container_name: postgres_db
    build:
      context: .
      dockerfile: dockerfile-db
    environment:
      POSTGRES_USER: alejo
      POSTGRES_PASSWORD: 1989
      POSTGRES_DB: iot_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - middleware-network

  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfile-app
    depends_on:
      - postgres_db
    environment:
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
      POSTGRES_USER: alejo
      POSTGRES_PASSWORD: 1989
      POSTGRES_DB: iot_db
    networks:
      - middleware-network

networks:
  middleware-network:
    driver: bridge